import XCTest
import CryptoKit
@testable import AgeKit

/// Tests for the `mlkem768p256tag` tagged post-quantum recipient (`age1tagpq…`).
///
/// This is a wrap-only recipient — the matching identity lives in a hardware
/// plugin — so correctness is pinned by encrypting to a recipient generated by
/// age-plugin-se and decrypting the result back with age + age-plugin-se. Skipped
/// unless both binaries are present and this Mac's Secure Enclave does ML-KEM.
@available(macOS 26, iOS 26, tvOS 26, watchOS 26, *)
final class MLKEM768P256Tests: XCTestCase {
    static let plaintext = "pqtag interop vector"

    func testAgePluginSeDecryptsOurCiphertext() throws {
        let age = try locate(["~/go/bin/age", "/opt/homebrew/bin/age", "/usr/local/bin/age"], "age v1.3+")
        let plugin = try locate([
            "~/src/age-plugin-se/.build/debug/age-plugin-se",
            "~/src/age-plugin-se/.build/release/age-plugin-se",
            "/opt/homebrew/bin/age-plugin-se",
        ], "age-plugin-se")
        let pluginDir = (plugin as NSString).deletingLastPathComponent

        let dir = FileManager.default.temporaryDirectory.appendingPathComponent("agekit-tagpq-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }

        // Generate a hardware post-quantum key with age-plugin-se.
        let keyPath = dir.appendingPathComponent("key.txt")
        let keygen = run(plugin, ["keygen", "--pq", "--recipient-type", "tag", "-o", keyPath.path])
        try XCTSkipUnless(keygen.status == 0, "age-plugin-se keygen --pq failed (no Secure Enclave ML-KEM?): \(str(keygen.stderr))")

        // Pull the age1tagpq recipient out of the key file's comment header.
        let keyFile = try String(contentsOf: keyPath, encoding: .utf8)
        guard let line = keyFile.split(separator: "\n").first(where: { $0.contains("public key (post-quantum):") }),
              let recipientString = line.split(separator: " ").last.map(String.init) else {
            return XCTFail("no post-quantum recipient in age-plugin-se output")
        }

        // Encrypt to it with our recipient.
        let recipient = try Age.MLKEM768P256Recipient(recipientString)
        let cipherPath = dir.appendingPathComponent("msg.age")
        try encrypt(recipient, Self.plaintext).write(to: cipherPath)

        // Decrypt with age, which invokes age-plugin-se from PATH.
        let decrypt = run(age, ["--decrypt", "-i", keyPath.path, cipherPath.path],
                          path: "\(pluginDir):/usr/bin:/bin")
        XCTAssertEqual(decrypt.status, 0, "age + age-plugin-se failed to decrypt our ciphertext: \(str(decrypt.stderr))")
        XCTAssertEqual(str(decrypt.stdout), Self.plaintext)
    }

    // MARK: Helpers

    private func locate(_ paths: [String], _ name: String) throws -> String {
        for p in paths {
            let expanded = (p as NSString).expandingTildeInPath
            if FileManager.default.isExecutableFile(atPath: expanded) { return expanded }
        }
        throw XCTSkip("\(name) not installed")
    }

    private func str(_ data: Data) -> String { String(decoding: data, as: UTF8.self) }

    private func run(_ executable: String, _ arguments: [String], path: String? = nil) -> (status: Int32, stdout: Data, stderr: Data) {
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: executable)
        proc.arguments = arguments
        if let path { proc.environment = ["PATH": path] }
        let out = Pipe(), err = Pipe()
        proc.standardOutput = out
        proc.standardError = err
        try? proc.run()
        let outData = out.fileHandleForReading.readDataToEndOfFile()
        let errData = err.fileHandleForReading.readDataToEndOfFile()
        proc.waitUntilExit()
        return (proc.terminationStatus, outData, errData)
    }

    private func encrypt(_ recipient: any Recipient, _ text: String) throws -> Data {
        var out = OutputStream.toMemory()
        out.open()
        var w = try Age.encrypt(dst: &out, recipients: recipient)
        _ = try w.write(text)
        try w.close()
        out.close()
        return out.property(forKey: .dataWrittenToMemoryStreamKey) as! Data
    }
}
